/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshopproject;

import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class BookSell extends javax.swing.JFrame {
  String S,S2;
  Date date= new Date();
  
    
    public BookSell() {
        initComponents();
        setLocationRelativeTo(null);
    }
      public BookSell(String s1,String s2) {
        initComponents();
        setLocationRelativeTo(null);
        S=s1;
        S2=s2;
        level.setText("("+s1+")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
       int i=0;
    double sum=0;
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        quantity = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        sell = new javax.swing.JButton();
        bid = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        level = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1201, 648));
        getContentPane().setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\start.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(850, 530, 360, 80);
        getContentPane().add(quantity);
        quantity.setBounds(190, 380, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Quantity:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 370, 60, 40);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Book Id", "Book name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(1).setMinWidth(140);
            table.getColumnModel().getColumn(1).setPreferredWidth(140);
            table.getColumnModel().getColumn(1).setMaxWidth(140);
            table.getColumnModel().getColumn(3).setMinWidth(80);
            table.getColumnModel().getColumn(3).setPreferredWidth(80);
            table.getColumnModel().getColumn(3).setMaxWidth(80);
            table.getColumnModel().getColumn(4).setMinWidth(80);
            table.getColumnModel().getColumn(4).setPreferredWidth(80);
            table.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(510, 0, 660, 260);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Enter  Book  Id :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 310, 130, 40);

        sell.setText("Sell");
        sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellActionPerformed(evt);
            }
        });
        getContentPane().add(sell);
        sell.setBounds(290, 450, 120, 23);
        getContentPane().add(bid);
        bid.setBounds(190, 320, 130, 30);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(50, 450, 120, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\49000213-wall-rough-texture-grey-color-background.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 260, 400, 290);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Total in Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(980, 250, 100, 50);

        total.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(total);
        total.setBounds(1070, 260, 100, 30);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(20, 20, 55, 23);

        level.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        getContentPane().add(level);
        level.setBounds(90, 570, 140, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setText("Log Out");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 580, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Java\\BookShopProject\\pic\\white-background-wallpaper-2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       
         try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshopproject","root","");
        String sql = "Select * from book where bid=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,bid.getText());
        ResultSet rs =pst.executeQuery();
        DefaultTableModel tm = (DefaultTableModel)table.getModel();
     
        tm.setRowCount(i);
        i++;
       
       
        
        while(rs.next())
            {
                
                  
               
                String s = String.valueOf(quantity.getValue());
               String a=rs.getString("prize");
               String e = date.toLocaleString();
               double b= Double.valueOf(a);
                double c = Double.valueOf(s);
                double d=b*c;
                sum=sum+d;
                String t=String.valueOf(d);
                Object o[]={e,rs.getString("bid"),rs.getString("bname"),s,t};
                tm.addRow(o);
                 total.setText(String.valueOf(sum)); 
                 try
                {
                 String query="INSERT INTO `bookrecord`(`Date`, `username`, `fname`, `bid`, `bname`, `quantity`, `price`) VALUES (?,?,?,?,?,?,?)";
                 Connection don = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshopproject","root","");
                  pst=don.prepareStatement(query);
                  pst.setString(1, e);
        
            pst.setString(2,S);
            pst.setString(3,S2);
             pst.setString(4,rs.getString("bid"));
              pst.setString(5,rs.getString("bname"));
               pst.setString(6,s);
                pst.setString(7,String.valueOf(d));
                  pst.executeUpdate();
               
            
                }
                catch (Exception E)
                {
                     JOptionPane.showMessageDialog(null, E);
                }
                
                
                
            }
   
        }
      
        catch(Exception e )
        {
         JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addActionPerformed

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
       JOptionPane.showMessageDialog(null, "Sold!!! You are doing  great job");
    }//GEN-LAST:event_sellActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         new Page1(S,S2).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Login l=new Login();
        l.show();
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked
       
    
    
    public static void main(String args[]) {
         
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JTextField bid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel level;
    private javax.swing.JSpinner quantity;
    private javax.swing.JButton sell;
    private javax.swing.JTable table;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
