/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshopproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class BookRegistration extends javax.swing.JFrame {
 String s,S2;
     Connection con = null;
    PreparedStatement pst = null;
    public BookRegistration() {
        initComponents();
        setLocationRelativeTo(null);
    }
      public BookRegistration(String s1,String s2) {
        initComponents();
        setLocationRelativeTo(null);
        s=s1;
        S2=s2;
         level.setText("("+s1+")");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bid = new javax.swing.JTextField();
        btext = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        aname = new javax.swing.JTextField();
        aprize = new javax.swing.JTextField();
        discount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnconfirm = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1201, 648));
        getContentPane().setLayout(null);
        getContentPane().add(bid);
        bid.setBounds(500, 130, 160, 30);

        btext.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btext.setForeground(new java.awt.Color(255, 255, 255));
        btext.setText("Book's id  ");
        getContentPane().add(btext);
        btext.setBounds(440, 110, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Publication's  name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 250, 140, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Actual Prize ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 310, 100, 15);

        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        getContentPane().add(pname);
        pname.setBounds(500, 280, 160, 30);
        getContentPane().add(bname);
        bname.setBounds(500, 180, 160, 30);
        getContentPane().add(aname);
        aname.setBounds(500, 230, 160, 30);
        getContentPane().add(aprize);
        aprize.setBounds(500, 330, 160, 30);

        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });
        getContentPane().add(discount);
        discount.setBounds(500, 380, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Discount");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 360, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Log Out");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 570, 100, 20);

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 20, 70, 23);

        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnconfirm);
        btnconfirm.setBounds(640, 440, 90, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Author's name ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 210, 100, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book's name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 150, 80, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\Bricks-Texture-Black-Background.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 60, 480, 440);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\start.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(850, 510, 360, 80);

        level.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        level.setText("sasdas");
        getContentPane().add(level);
        level.setBounds(90, 550, 140, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Java\\BookShopProject\\pic\\white-background-wallpaper-2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        if(bid.getText().equals("")||aname.getText().equals("")||pname.getText().equals("")||aprize.getText().equals("")||discount.getText().equals(""))
         {
           JOptionPane.showMessageDialog(null,"Fill Up The Every Empty Filed");
         
         }
        else
        {
                   try{
        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshopproject","root","");
        String sql = "SELECT * FROM `book` WHERE bid=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,bid.getText());
        String s = bid.getText();
        ResultSet rs =pst.executeQuery();
        if(rs.next())
        {
               JOptionPane.showMessageDialog(null, s +" Book id Already used");
               bid.setText("");
               
               
        }
        else
        {
                  try{
           
         
            String query="INSERT INTO `book`(`bid`, `bname`, `aname`, `pname`, `aprize`, `discount`, `prize`) VALUES (?,?,?,?,?,?,?)";
           Connection don = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshopproject","root","");
            pst=don.prepareStatement(query);
            pst.setString(1, bid.getText());
           
            pst.setString(2, bname.getText());
            pst.setString(3, aname.getText());
             pst.setString(4, pname.getText());
            pst.setString(5, aprize.getText());
            pst.setString(6, discount.getText());
            double acprize=Double.valueOf(aprize.getText());
            double dis=Double.valueOf(discount.getText());
            double prize=acprize-((dis/100)*acprize);
            pst.setString(7, String.valueOf(prize));
              //pst.setString(7, discount.getText());
            pst.executeUpdate();
            String a=bname.getText();
            
             JOptionPane.showMessageDialog(null,"Yap "+a+" registered..Great Job");
           bid.setText("");
             bname.setText("");
             aname.setText("");
             pname.setText("");
             aprize.setText("");
             discount.setText("");
             
            }
         catch(Exception e)
         {
         JOptionPane.showMessageDialog(null,e);
         }
        
        
        }
        }
        
        
        catch (Exception ex)
                {
                JOptionPane.showMessageDialog(null,ex);
                
                 }
        }
        
        
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Page1(s,S2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Login l=new Login();
        l.show();
      
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked
   
    
    public static void main(String args[]) {
      
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aname;
    private javax.swing.JTextField aprize;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bname;
    private javax.swing.JLabel btext;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JTextField discount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel level;
    private javax.swing.JTextField pname;
    // End of variables declaration//GEN-END:variables
}
