package bookshopproject;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
//import logindata.myconverter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class CalculatorMaking extends javax.swing.JFrame {
private static String action = "";
private static double num1=0.0;
private static double num2;
private static double result;
private static boolean cheak = true;
private static double num3;


    public CalculatorMaking() {
        initComponents();
          display.addKeyListener(new KeyAdapter() {
    @Override
    public void keyTyped(KeyEvent e) {
        char ch = e.getKeyChar();

        if (!isNumber(ch)) {
            e.consume();
        }
    }
     

        
        });
           
       
         setLocationRelativeTo(null);
    }
    private  boolean isNumber(char ch) {
                     return ch >= '.' && ch <= '9';            };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bequal = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        bplus = new javax.swing.JButton();
        bminus = new javax.swing.JButton();
        bmultiple = new javax.swing.JButton();
        bdevide = new javax.swing.JButton();
        ACE = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bsqrt = new javax.swing.JButton();
        bsquare = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btncc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(314, 541));
        setUndecorated(true);
        getContentPane().setLayout(null);

        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display);
        display.setBounds(43, 50, 220, 41);

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(39, 198, 39, 23);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(84, 198, 39, 23);

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(129, 198, 39, 23);

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(39, 169, 39, 23);

        b5.setText("6");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(129, 169, 39, 23);

        b6.setText("5");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(84, 169, 39, 23);

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(39, 140, 39, 23);

        b8.setText("9");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(129, 140, 39, 23);

        b9.setText("8");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(84, 140, 39, 23);

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0);
        b0.setBounds(39, 232, 39, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Calculator");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 10, 80, 30);

        bequal.setText("=");
        bequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequalActionPerformed(evt);
            }
        });
        getContentPane().add(bequal);
        bequal.setBounds(129, 232, 130, 23);

        bcancel.setText("Cancel");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        getContentPane().add(bcancel);
        bcancel.setBounds(20, 490, 80, 23);

        bplus.setText("+");
        bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bplusActionPerformed(evt);
            }
        });
        getContentPane().add(bplus);
        bplus.setBounds(174, 198, 41, 23);

        bminus.setText("-");
        bminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bminusActionPerformed(evt);
            }
        });
        getContentPane().add(bminus);
        bminus.setBounds(221, 198, 41, 23);

        bmultiple.setText("*");
        bmultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmultipleActionPerformed(evt);
            }
        });
        getContentPane().add(bmultiple);
        bmultiple.setBounds(174, 169, 41, 23);

        bdevide.setText("/");
        bdevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdevideActionPerformed(evt);
            }
        });
        getContentPane().add(bdevide);
        bdevide.setBounds(221, 169, 41, 23);

        ACE.setBackground(new java.awt.Color(255, 51, 51));
        ACE.setText("ACE");
        ACE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEActionPerformed(evt);
            }
        });
        getContentPane().add(ACE);
        ACE.setBounds(39, 104, 84, 23);

        bdot.setText(".");
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });
        getContentPane().add(bdot);
        bdot.setBounds(84, 232, 39, 23);

        jButton1.setText("<--");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(174, 140, 90, 23);

        bsqrt.setBackground(new java.awt.Color(0, 0, 0));
        bsqrt.setForeground(new java.awt.Color(255, 255, 255));
        bsqrt.setText("sqrt");
        bsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsqrtActionPerformed(evt);
            }
        });
        getContentPane().add(bsqrt);
        bsqrt.setBounds(129, 104, 76, 23);

        bsquare.setBackground(new java.awt.Color(0, 0, 0));
        bsquare.setForeground(new java.awt.Color(255, 255, 255));
        bsquare.setText("<html>\n\nx<sup>2</sup>\n</html>\n");
        bsquare.setActionCommand("<html>\nx<sup>2</sup>\n</html>");
        bsquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsquareActionPerformed(evt);
            }
        });
        getContentPane().add(bsquare);
        bsquare.setBounds(211, 104, 53, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\Calculator\\pencil-calculator-notebook-letters-white-background-125098568.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 280, 320, 194);

        btncc.setText("Currency Converter");
        btncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccActionPerformed(evt);
            }
        });
        getContentPane().add(btncc);
        btncc.setBounds(160, 490, 140, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\Calculator\\calculator-background-1918x999.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 320, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
      // display.setText("");
        String str;
        str = display.getText()+b1.getText();
        display.setText(str);
    }//GEN-LAST:event_b1ActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
      
        String arr;
        num1=0;
        arr=display.getText();
        int i;
        for(i=0; ; i++)
        {
         if("+".equals(arr.charAt(i)))
         {
             action = "+";
             cheak=false;
             num3= i;
             break;
         }
         num1=num1+Double.valueOf(arr.charAt(i));
         
        }
            
            
             
    }//GEN-LAST:event_displayActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
         //display.setText("");
        String str;
        str = display.getText()+b2.getText();
        display.setText(str);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // display.setText("");
        String str;
        str = display.getText()+b3.getText();
        display.setText(str);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       // display.setText("");
       String str;
        str = display.getText()+b4.getText();
        display.setText(str);
    }//GEN-LAST:event_b4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
      // display.setText("");
        String str;
        str = display.getText()+b6.getText();
        display.setText(str);
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // display.setText("");
        String str;
        str = display.getText()+b5.getText();
        display.setText(str);
    }//GEN-LAST:event_b5ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // display.setText("");
        String str;
        str = display.getText()+b7.getText();
        display.setText(str);
    }//GEN-LAST:event_b7ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
       // display.setText("");
        String str;
        str = display.getText()+b9.getText();
        display.setText(str);
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        //  display.setText("");
        String str;
        str = display.getText()+b8.getText();
        display.setText(str);
    }//GEN-LAST:event_b8ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
          //display.setText("");
        String str;
        str = display.getText()+b0.getText();
        display.setText(str);
    }//GEN-LAST:event_b0ActionPerformed

    private void bequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequalActionPerformed
       if(cheak)
        num2 =Double.valueOf(display.getText());
       else
       {
           String s;
           s=display.getText();
           num2=0;
           for(int i =(int) (num3+1);i<s.length();i++)
           {
             num2=num2+Double.valueOf(s.charAt(i));
             cheak=true;
           }
       }
       if("+".equals(action))
       {
        result = (double)(num1+num2);
        num1=0;
        num2=0;
       }
        if("-".equals(action))
       {
        result = (double)(num1-num2);
        num1=0;
        num2=0;
       }
         if("*".equals(action))
       {
        result = (double)(num1*num2);
        num1=0;
        num2=0;
       }
          if("/".equals(action))
       {
        result = (double)(num1/num2);
        num1=0;
        num2=0;
       }
          display.setText(String.valueOf(result));
         // num1=(int)result;
          
        
          //display.setText("");
    }//GEN-LAST:event_bequalActionPerformed
      
    private void bplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bplusActionPerformed
        action = "+";
         // num1=(int)result;
        num1 = num1+Double.valueOf(display.getText());
        display.setText("");
    }//GEN-LAST:event_bplusActionPerformed

    private void bminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bminusActionPerformed
          action = "-";
        num1 = num1+Double.valueOf(display.getText());
        display.setText("");
    }//GEN-LAST:event_bminusActionPerformed

    private void bmultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmultipleActionPerformed
         action = "*";
         num1 = num1+Double.valueOf(display.getText());
        display.setText("");
    }//GEN-LAST:event_bmultipleActionPerformed

    private void bdevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdevideActionPerformed
         action = "/";
       num1 = num1+Double.valueOf(display.getText());
        display.setText("");
    }//GEN-LAST:event_bdevideActionPerformed

    private void ACEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEActionPerformed
            display.setText("");
    }//GEN-LAST:event_ACEActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
          String str;
        str = display.getText()+bdot.getText();
        display.setText(str);
    }//GEN-LAST:event_bdotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s;
        s = display.getText();
        s=s.substring(0,s.length()-1);
        display.setText(s);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsqrtActionPerformed
                num1=Double.valueOf(display.getText());
                num1=Math.sqrt(num1);
                display.setText(String.valueOf(num1));
                  num1=0;
    }//GEN-LAST:event_bsqrtActionPerformed

    private void bsquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsquareActionPerformed
              num1=Double.valueOf(display.getText());
              num1=num1*num1;
              display.setText(String.valueOf(num1));
              num1=0;
    }//GEN-LAST:event_bsquareActionPerformed

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_bcancelActionPerformed

    private void btnccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccActionPerformed
    cls();
    }//GEN-LAST:event_btnccActionPerformed
    private void cls()
     {
         this.dispose();
         myconverter cm = new myconverter ();
         cm.show();
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorMaking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorMaking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorMaking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorMaking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorMaking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACE;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bdevide;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bminus;
    private javax.swing.JButton bmultiple;
    private javax.swing.JButton bplus;
    private javax.swing.JButton bsqrt;
    private javax.swing.JButton bsquare;
    private javax.swing.JButton btncc;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
