/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshopproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Page1 extends javax.swing.JFrame {

    String s2,s3;
    public Page1() {
        initComponents();
        setLocationRelativeTo(null);
    }
      public Page1(String s1,String s4) {
           initComponents();
           setLocationRelativeTo(null);
              level.setText("("+s1+")");
              s2=s1;
              s3=s4;
              
               
                 
           
      }
    
      
     
      
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        al = new javax.swing.JLabel();
        bl = new javax.swing.JLabel();
        displayl = new javax.swing.JLabel();
        dl = new javax.swing.JLabel();
        idl = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        pname = new javax.swing.JLabel();
        pl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        acl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pcl = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        Bid = new javax.swing.JLabel();
        aprize = new javax.swing.JLabel();
        aname = new javax.swing.JLabel();
        Bname = new javax.swing.JLabel();
        prize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1201, 648));
        getContentPane().setLayout(null);

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 310, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Book's Id :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 250, 80, 30);
        getContentPane().add(bid);
        bid.setBounds(610, 250, 130, 30);

        al.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(al);
        al.setBounds(900, 140, 80, 20);

        bl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(bl);
        bl.setBounds(900, 100, 80, 20);

        displayl.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(displayl);
        displayl.setBounds(930, 20, 220, 30);

        dl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(dl);
        dl.setBounds(930, 260, 70, 30);

        idl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(idl);
        idl.setBounds(920, 60, 90, 30);
        getContentPane().add(bname);
        bname.setBounds(610, 210, 130, 30);

        pname.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(pname);
        pname.setBounds(1000, 180, 240, 30);

        pl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(pl);
        pl.setBounds(910, 180, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Book's Name: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 210, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\book.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 60, 520, 450);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\start.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(850, 510, 360, 80);

        acl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(acl);
        acl.setBounds(910, 220, 80, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setText("Log Out");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 550, 60, 30);

        pcl.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(pcl);
        pcl.setBounds(940, 310, 50, 20);

        discount.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(discount);
        discount.setBounds(1000, 260, 210, 30);

        level.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        getContentPane().add(level);
        level.setBounds(80, 540, 140, 50);

        Bid.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(Bid);
        Bid.setBounds(1000, 60, 220, 30);

        aprize.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(aprize);
        aprize.setBounds(1000, 220, 240, 30);

        aname.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(aname);
        aname.setBounds(1000, 130, 190, 40);

        Bname.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(Bname);
        Bname.setBounds(1000, 94, 220, 30);

        prize.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        getContentPane().add(prize);
        prize.setBounds(1000, 304, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Java\\BookShopProject\\pic\\white-background-wallpaper-2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 670);

        jMenu3.setText("Section");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Sell Section");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Book Registration");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Accesories");

        jMenuItem3.setText("Calculator");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Currency Converter");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshopproject","root","");
        String sql = "Select * from book where bname=? or bid=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,bname.getText());
        pst.setString(2,bid.getText());
        ResultSet rs =pst.executeQuery();
        if(rs.next())
        {
            
            Bid.setText(rs.getString("bid"));
            Bname.setText(rs.getString("bname"));
            aname.setText(rs.getString("aname"));
            pname.setText(rs.getString("pname"));
             String a=rs.getString("aprize")+" Taka";
            aprize.setText(a);
             a=rs.getString("discount")+" %";
            discount.setText(a);
             a=rs.getString("prize")+" Taka";
            prize.setText(a);
            idl.setText("Book Id:");
            bl.setText("Book's Name :");
              al.setText("Author name:");
           pl.setText("Publication:");
           acl.setText("Actual Price:");
           dl.setText("Dicount:");
           pcl.setText("Price:");
           displayl.setText("Information About The Book");
              
            
              
               
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Ops!!! Sorry!!! We don't have the book");
             bid.setText("");
             bname.setText("");
             Bid.setText("");
             Bname.setText("");
             aname.setText("");
             pname.setText("");
             aprize.setText("");
             discount.setText("");
             prize.setText("");
             idl.setText("");
            bl.setText("");
              al.setText("");
           pl.setText("");
           acl.setText("");
           dl.setText("");
           pcl.setText("");
              
        }
        }
        catch(Exception e )
        {
         JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Login l=new Login();
        l.show();
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     new BookRegistration(s2,s3).setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       new BookSell(s2,s3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CalculatorMaking cm = new CalculatorMaking();
        cm.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         myconverter my = new myconverter();
        my.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new Page1().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bid;
    private javax.swing.JLabel Bname;
    private javax.swing.JLabel acl;
    private javax.swing.JLabel al;
    private javax.swing.JLabel aname;
    private javax.swing.JLabel aprize;
    private javax.swing.JTextField bid;
    private javax.swing.JLabel bl;
    private javax.swing.JTextField bname;
    private javax.swing.JLabel discount;
    private javax.swing.JLabel displayl;
    private javax.swing.JLabel dl;
    private javax.swing.JLabel idl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel level;
    private javax.swing.JLabel pcl;
    private javax.swing.JLabel pl;
    private javax.swing.JLabel pname;
    private javax.swing.JLabel prize;
    // End of variables declaration//GEN-END:variables
}
