/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshopproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Registration extends javax.swing.JFrame {

   
    Connection con = null;
    PreparedStatement pst = null;
    public Registration() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox();
        cfnpassword = new javax.swing.JPasswordField();
        fname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1201, 648));
        getContentPane().setLayout(null);

        btngo.setBackground(new java.awt.Color(153, 153, 255));
        btngo.setText("Sing Up");
        btngo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoActionPerformed(evt);
            }
        });
        getContentPane().add(btngo);
        btngo.setBounds(620, 430, 90, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 230, 230, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("Firstname");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 240, 90, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("Username");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(620, 300, 210, 30);
        getContentPane().add(username);
        username.setBounds(620, 330, 200, 30);
        getContentPane().add(phone);
        phone.setBounds(350, 330, 230, 30);

        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(gender);
        gender.setBounds(620, 270, 200, 30);
        getContentPane().add(cfnpassword);
        cfnpassword.setBounds(620, 390, 200, 30);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname);
        fname.setBounds(350, 270, 230, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\sometimes-sabr-and-silence-is-better-than-expressing-how-you-23741887.png")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 180, 210, 180);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("Confirm Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(620, 360, 190, 30);
        getContentPane().add(password);
        password.setBounds(350, 390, 230, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Back To The Login ");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(540, 480, 160, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\start.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(880, 540, 330, 70);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Mobile number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 300, 200, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\emoji-smiling-man-picking-bag-600w-1010145049.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 170, 60, 62);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setText("Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 360, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\wall-wallpaper-concrete-colored-painted-textured-concept_53876-31799.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 100, 630, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Java\\BookShopProject\\pic\\white-background-wallpaper-2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        
    }//GEN-LAST:event_fnameActionPerformed

    private void btngoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoActionPerformed
         if(fname.getText().equals("")||phone.getText().equals("")||username.getText().equals("")||password.getText().equals(""))
         {
           JOptionPane.showMessageDialog(null,"Fill Up The Every Empty Filed");
         
         }
         else
         {
               try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshopproject","root","");
        String sql = "Select * from login where username=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,username.getText());
        String s = username.getText();
        ResultSet rs =pst.executeQuery();
        if(rs.next())
        {
               JOptionPane.showMessageDialog(null, s +" Username Already used");
               username.setText("");
               
               
        }
        else
        {
                   
                 try
            {
         
            String query="INSERT INTO `login`(`fname`, `gender`, `phone`, `username`, `password`) VALUES (?,?,?,?,?)";
           Connection don = DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshopproject","root","");
            pst=don.prepareStatement(query);
            pst.setString(1, fname.getText());
           
            pst.setString(2, gender.getSelectedItem().toString());
            pst.setString(3, phone.getText());
             pst.setString(4, username.getText());
             String str1=password.getText();
             String str2=cfnpassword.getText();
             if(str1.equals(str2))
             {
            pst.setString(5, password.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"You are registerd");
            cls();
             }
             else
             {
              JOptionPane.showMessageDialog(null,"Confirm Password Correctly");
              
             }
            
            }
         catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,e);
        }
        }
        }
        catch(Exception e )
        {
         JOptionPane.showMessageDialog(null, e);
        }
         
         }
    }
                                        
 private void cls()
    {
         this.dispose();
        Login WPass= new Login ();
         WPass.show();
      
     }
    /**
    }//GEN-LAST:event_btngoActionPerformed
**/
    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
       go();
    }//GEN-LAST:event_jLabel12MouseClicked
  private void go()
  {
      this.dispose();
      Login p=new Login();
      p.show();
  }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngo;
    private javax.swing.JPasswordField cfnpassword;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
